# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Install necessary network utilities.
# These packages are often missing from slim images and are
# required for DNS resolution and other networking tasks.
RUN apt-get update && apt-get install -y dnsutils libgssapi-krb5-2

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define the command to run the application
CMD ["uvicorn", "gateway_service:app", "--host", "0.0.0.0", "--port", "8000"]
